# general global config across all listeners of all network protocols 

domains = [ "dssldrf.net" ]

public_ips = [ "20.118.179.161", "20.118.177.227" ]

# database connections metadata
[db]
min_conn = 2
max_conn = 20

# logging and telemetry
[appinsights]
connstr="InstrumentationKey=d878dcae-7f04-470d-bb82-8a7e338c8106;IngestionEndpoint=https://centralus-2.in.applicationinsights.azure.com/;LiveEndpoint=https://centralus.livediagnostics.monitor.azure.com/"

# listeners for each network protocol
[listeners]

[listeners.dns]
port = 53
udp = true
prefix_len = 12

[listeners.http]
port = 80

[listeners.https]
port = 443
tls = true 
crt_file = "/mnt/secrets/dssldrf-canary-cert"
key_file = "/mnt/secrets/dssldrf-canary-cert"
