# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: dusseldorf-api-lb
#   namespace: default
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-ipv4: "{{ .Values.global.loadBalancerIP2 }}"  # Assign multiple IPs
# spec:
#   type: LoadBalancer
#   selector:
#     app: dusseldorf-api
#   ports:
#     - name: api
#       port: 443
#       targetPort: 443
#       protocol: TCP