apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-csi
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: csi-secrets
    type: Opaque
    data:
    - objectName: {{ .Values.secrets.keyVaultSecretName }}
      key: app-secret
    - objectName: {{ .Values.secrets.certSecretName }}
      key: cert-secret  # Only for HTTPS Listener
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.global.identityName }}
    keyvaultName: {{ .Values.secrets.keyVaultName }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secrets.keyVaultSecretName }}
          objectType: secret
        - |
          objectName: {{ .Values.secrets.certSecretName }}
          objectType: secret 
    tenantId: {{ .Values.global.tenantID }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-csi-api
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: csi-secrets
    type: Opaque
    data:
    - objectName: {{ .Values.secrets.keyVaultSecretName }}
      key: app-secret
    - objectName: {{ .Values.secrets.apiCertName }}
      key: api-cert-secret  # Only for API Listener
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.global.identityName }}
    keyvaultName: {{ .Values.secrets.keyVaultName }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secrets.keyVaultSecretName }}
          objectType: secret
        - |
          objectName: {{ .Values.secrets.apiCertName}}
          objectType: secret
    tenantId: {{ .Values.global.tenantID }}