apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dusseldorfkv-user-msi
spec:
  provider: azure
  secretObjects:
  - secretName: dssldrf-dataplane-connstr
    type: Opaque
    data:
    - objectName: dssldrf-dataplane-connstr
      key:  dssldrf-dataplane-connstr
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: 470da2b0-d68b-4efd-ba9b-9d2ecad9fee7
    keyvaultName: dssldrf-canary
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47 
    cloudName: "AzurePublicCloud"                         
    objects:  |
      array:
        - |
          objectName: dssldrf-dataplane-connstr
          objectType: secret          
          objectVersion: ""