version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    ports:
      - "8000:8000"
      - "5678:5678"  # For debugging

  mongo:
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null  # Disable logging in development 