version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB_NAME=dusseldorf
      - AZURE_TENANT_ID=72f988bf-86f1-41af-91ab-2d7cd011db47
      - AZURE_CLIENT_ID=dc1b6b75-8167-4baf-9e75-d3d1f755de1b
#      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
      - API_VERSION=2.0.0
      - ENVIRONMENT=${ENVIRONMENT:-production}
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    networks:
      - dusseldorf-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dusseldorf-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dusseldorf-network:
    driver: bridge

volumes:
  mongodb_data: 